name: Update Weather Data

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    env:
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script to fetch live weather
        run: python scripts/fetch_live_weather.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/live_weather.csv
          git commit -m "Update weather data [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
