name: Update Live Weather CSV

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}  # ✅ Ensure this secret is set

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script to fetch weather data
        run: python scripts/fetch_live_weather.py

      - name: Commit and Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/live_weather.csv
          git commit -m "Update weather data [auto]" || echo "No changes to commit"
          git push origin main
