name: update-weather

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather fetch script
        run: python scripts/fetch_live_weather.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Pull with rebase to avoid rejection
          git pull --rebase origin main

          git add data/live_weather.csv
          git commit -m "Update weather data [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
