name: update-weather

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Required to push with GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ✅ Needed to allow push using GITHUB_TOKEN

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run weather fetch script
        run: python scripts/fetch_live_weather.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git pull --rebase origin main || true
          git add data/live_weather.csv

          git commit -m "Update weather data [auto]" || echo "No changes to commit"
          git push
